services:
  app:
    image: yakssok/yakssok:${TAG}
    container_name: yakssok-app
    ports:
      - "8080:8080"
    networks:
      - internal
    restart: unless-stopped
    environment:
      SPRING_AUTOCONFIGURE_EXCLUDE: "org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration"
      MANAGEMENT_METRICS_ENABLE_SYSTEM: "false"
      MANAGEMENT_METRICS_ENABLE_PROCESS: "false"
      MANAGEMENT_METRICS_BINDERS_PROCESSOR_ENABLED: "false"

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge
