name: yakssok-deploy-render
on:
  push:
    branches: [ "release/supabase" ]
    paths:
      - "yakssok/**"
      - ".github/workflows/yakssok-deploy-render.yml"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: 🧾 Checkout
        uses: actions/checkout@v3

      - name: 🔧 Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 📦 Build and Push Docker Image
        run: |
          cd yakssok
          echo "🔐 Create application.yml"
          mkdir -p src/main/resources
          echo "${{ secrets.PROD_YML_SUPABASE }}" > src/main/resources/application.yml

          echo "🔐 Create firebase key json"
          echo '${{ secrets.FIREBASE_KEY_JSON }}' > src/main/resources/firebase-service-account.json

          echo "🏗️ Build Spring Boot"
          chmod +x ./gradlew
          ./gradlew build -x test

          echo "🐳 Docker Build & Push"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t yakssok/yakssok:${IMAGE_TAG} \
            -t yakssok/yakssok:latest \
            --push .
